src/commands/release.ts

Adds a link to the GitHub compare interface to make it easier to visually
compare changes performed by craft.
```
$ craft release --no-changelog 5.1.1
...
ℹ info Pushing the release branch "release/5.1.1"...
ℹ info View diff at: https://github.com/getsentry/symbolic/compare/release/5.1.1
✔ success Done. Do not forget to run "craft publish" to publish the artifacts:
$ craft publish 5.1.1
```

feat: Show link to diff after `craft release`

---

src/commands/prepare.ts

This will no longer print the error
```
⚠ warn Not running the pre-release command: no command specified
✖ error Error: Nothing to commit: has the pre-release command done its job?
```
if the `preReleaseCommand` is defined as empty string.

Allow empty preReleaseCommand

---

src/utils/__tests__/changes.test.ts
src/utils/changes.ts

We have the date in the changelog file in the PHP repo. It makes sense in the file itself but not that it's pasted in the GH title imho.

feat: Ignore date for gh release title in changelog

---

src/targets/crates.ts

Instead of downloading a source tarball from GitHub, clone the release branch with submodules instead. This allows to publish crates like `symbolic` that depend on shipping code from submodules.
Noteworthy points:
- This performs a **shallow clone** (`--depth=1`) to reduce the time this takes.
- There is no straight-forward option to directly shallow clone an arbitrary commit SHA, so instead this clones the release branch. Since the branch is checked against Zeus immediately beforehand, we can assume that the branch head revision matches.
- The clone is performed with `--recurse`, which initializes submodules. If the repository does not specify shallow submodules, this might take quite a while, but that is out of scope of this PR. We could pass `--shalllow-submodules`, but that comes with …

feat(crates): Clone with submodules before publishing

---

src/targets/npm.ts

We published `@sentry/*` with `5.0.0-beta1` & `5.0.0-beta.2` to the npm registry.
Apparently, npm needs a tag with `--tag=next` to not make it `latest` which means it will be the default when doing `npm install @sentry/browser` for example.
Without `--tag=next` you would get the highest version, in our case `5.0.0-beta.2`.
We actually never ever want this to happen (imho) that's why I added this check to make sure we always add `--tag=next` in case it's a pre-release version.
We had to unpublish both version from npm 😞

feat/fix: Add tag next for npm prereleases

---

package.json
yarn.lock

Lots have changed, but apparently our usage of yargs didn't run into
any of the breaking changes:
https://github.com/yargs/yargs/compare/v12.0.5...v15.1.0
Fixes #38.
---
Fails when a bad flag is passed:
```
~/s/craft ❯❯❯ yarn cli prepare --not-a-flag --dry-run 0.1.0                                                                                                     rhcarvalho/bump-yargs
yarn run v1.21.1
$ run-s build
$ yarn run compile-config-schema && tsc -p tsconfig.build.json
$ node ./scripts/config-json-schema-to-ts.js
$ node dist prepare --not-a-flag --dry-run 0.1.0
ℹ info craft 0.9.0
ℹ info [dry-run] Dry-run mode is on!
dist prepare NEW-VERSION
🚢 Prepare a new release branch
Positionals:
NEW-VERSION  The new version you want to release           [string] [required]
Options: …
```

build(deps): Bump yargs to fix handling of bad flags

---

package.json
yarn.lock

@Swatinem noticed that with git 2.25.0 he's receiving errors when preparing a release. I'm hoping that this update resolves it. Didn't test anything yet.

build: Update simple-git

---

README.md

As a naive reader of this doc, it wasn't obvious to me that the GitHub params needed to point to the repo for the package you want to release, rather than always pointing to the `craft` repo. This hopefully clarifies that.

ref(README): Clarify GitHub project parameter example

---

README.md
src/commands/prepare.ts

This enables users to use craft to prepare releases targeting a remote
different than origin. For example, some people clone repositories such
that the remote 'origin' points to a fork and the remote 'upstream'
points to the upstream project repository.
Note that the string 'origin' is also found in ghPages.ts and
registry.ts, but those usages refer to a remote in a temporary clone
owned by craft and thus takes no customization.

feat: Support for custom remote names

---

.vscode/extensions.json

We currently recommend [this version](https://marketplace.visualstudio.com/items?itemName=eg2.tslint), which has been deprecated in favor of [this one](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin).

fix(vscode): Update extension recommendation for tslint

---

README.md
package.json
src/artifact_providers/base.ts
src/artifact_providers/none.ts
src/artifact_providers/zeus.ts
src/commands/artifacts.ts
src/commands/artifacts_cmds/download.ts
src/commands/artifacts_cmds/list.ts
src/commands/publish.ts
src/config.ts
src/status_providers/base.ts
src/status_providers/github.ts
src/status_providers/zeus.ts
src/stores/zeus.ts
src/targets/__tests__/crates.test.ts
src/targets/base.ts
src/targets/brew.ts
src/targets/cocoapods.ts
src/targets/crates.ts
src/targets/gcs.ts
src/targets/ghPages.ts
src/targets/github.ts
src/targets/npm.ts
src/targets/nuget.ts
src/targets/pypi.ts
src/targets/registry.ts
src/utils/version.ts
yarn.lock

This PR replaces all usages of the legacy ZeusStore with BaseArtifactProvider.
Zeus is still used as the default artifact provider, but we can now add new providers, yay.

 feat: Use artifact provider for publishing 

---

src/artifact_providers/base.ts
src/artifact_providers/none.ts
src/artifact_providers/zeus.ts

This makes explicit things which weren't obvious to me, as a newcomer to the codebase. Specifically:
1) I tried to differentiate between `XXX` methods, which rely on caching when they can, and `doXXX` methods, which always get their data from the provider.
2) I made sure every docstring included all parameters and the return value (if there was one).
3) Where paths are local, I tried to call them out as such.
4) When possible, I let subclass implementations of abstract methods inherit their docstrings from the base class.

ref(docs): Clarify artifact provider docstrings

---

src/__tests__/config.test.ts
src/commands/publish.ts
src/config.ts
src/index.ts
src/utils/__tests__/env.test.ts
src/utils/env.ts

With the introduction of the CGS artifact provider, we now have need for a function like [this](https://github.com/getsentry/craft/blob/2f623facdf151fde646e7746e93a8f6b3e902a60/src/commands/publish.ts#L100-L118) in multiple places, so this PR factors it out into its own module and makes it more generic. (It also moves all other env-related stuff to the new module.)
~I've marked this WIP until I can resolve two outstanding questions:~
~1) I've included unit tests for the function itself, but not any integration/acceptance/etc tests. So, in particular, though I've manually tested the fact that this doesn't break publishing (in other words, that that the generic function with specific parameters correctly mimics the behavior of the single-use function it's replacing), I have not written …

ref(config): Create environment utils module

---

src/artifact_providers/base.ts
src/artifact_providers/zeus.ts
src/commands/artifacts_cmds/download.ts
src/commands/artifacts_cmds/list.ts
src/commands/publish.ts
src/targets/brew.ts
src/targets/gcs.ts
src/targets/github.ts
src/targets/npm.ts
src/targets/nuget.ts
src/targets/pypi.ts
src/targets/registry.ts

Our current `CraftArtifact` interface is based on `zeus`'s `Artifact` interface. However, since we're working to include options besides `zeus` (and eventually move away from it all together), there's no reason we have to be tied to that format.
This refactors the interface so that property names are
- a little more explicit, 
- all in camel case, 
- consistent with the way things are named in the upcoming `GCSArtifactProvider`, and
- organized in such a way that it's clear what information is about the file in general, and what information is specifically about the copy of the file which lives on the artifact store.

ref(artifact providers): Refactor CraftArtifact interface

---

README.md
src/artifact_providers/base.ts
src/artifact_providers/zeus.ts
src/targets/gcs.ts
src/utils/__tests__/gcsAPI.test.ts
src/utils/gcsApi.ts

In preparation for the upcoming CGS artifact provider, this pulls all code from the GCS target module which might also useful to the artifact provider, collects it in a new GCS API module, and refactors the GCS target to use it.

ref(targets): Create GCS API module

---

package.json
src/commands/prepare.ts
src/commands/publish.ts
src/index.ts
src/targets/brew.ts
src/targets/ghPages.ts
src/targets/github.ts
src/targets/npm.ts
src/targets/registry.ts
src/types/dryrun.d.ts
src/utils/__tests__/gcsAPI.test.ts
src/utils/__tests__/helpers.test.ts
src/utils/errors.ts
src/utils/gcsApi.ts
src/utils/githubApi.ts
src/utils/helpers.ts
src/utils/system.ts

As recommended by various folks, vendor the env var check ourselves instead of relying on a package. Works identically to the package except:
1) the dry-run status is never cached, and
2) instead of two functions (`isDryRun` and `shouldPerform`, which are opposites), this only includes the former, for simplicity.
This also adds one test to the GCS client test suite which wasn't working because of the caching behavior of the package.

chore(dependencies): Remove `node-dryrun` dependency

---

src/artifact_providers/base.ts
src/artifact_providers/none.ts
src/artifact_providers/zeus.ts
src/config.ts
src/targets/base.ts
src/targets/gcs.ts
src/targets/npm.ts
src/targets/nuget.ts
src/targets/pypi.ts
src/targets/registry.ts
src/utils/__tests__/gcsAPI.test.ts
src/utils/gcsApi.ts

A few different changes to interfaces and other inner workings of artifact providers. See individual commits for details. 
(Oh, and now the GCS client tests have way more squirrels in them. Hey, I had to do _something_ to amuse myself while on lockdown!)

ref(artifact providers): Assorted clean up and tweaks

---

src/utils/__tests__/async.test.ts
src/utils/async.ts
src/utils/errors.ts

The basic idea of dry-run mode is to go through the entire process, with no side effects, reporting what would happen and/or any errors which occur. Currently, however, errors inside of a `forEachChained` call break the chain, so that the user can't see what would have happened had the rest of the links executed.
This PR fixes that by catching errors while executing each link. In order to accomplish the report-error-when-dry-run-throw-error-when-not behavior, it modifies the existing `reportError` function (which already does that with error _messages_) to also accept `Error` objects. Finally, it adds tests for each mode, with both sync and async iteratees.

feat(dry-run): Let dry run keep going after errors in `forEachChained`

---

src/logger.ts
src/utils/errors.ts
src/utils/sentry.ts

If the SDK hasn't yet been initialized (meaning the hub has no client bound to it), then all client methods (including `captureException`) [are no-ops](https://github.com/getsentry/sentry-javascript/blob/fd68dfa266fbea7c93712692aa8cfac7d6572802/packages/hub/src/hub.ts#L70-L75), and `addBreadcrumb` [is a no-op](https://github.com/getsentry/sentry-javascript/blob/fd68dfa266fbea7c93712692aa8cfac7d6572802/packages/hub/src/hub.ts#L238-L240), so it's safe to call them without checking the SDK's initialization status. Further, if the SDK _has_ already been initialized, then calling `init` again just replaces the bound client [with an identical client](https://github.com/getsentry/sentry-javascript/blob/a047ef28b9164597c8a57678810263d568f9d1b7/packages/hub/src/hub.ts#L87-L93), so it also doesn't …

fix(sentry): Remove initialization guard on sentry methods

---

src/commands/publish.ts

In dry-run mode, errors don't actually stop iteration of a for loop (since they're just logged, not thrown), so it's possible to make it all the way through a fail-fast loop, even having failed on at least one iteration. Therefore, we can't assume that just because we made it past the for loop, the test succeeded.
This adds a flag and a check of that flag, so that we report the correct result in dry-run mode.

fix(dry-run): Fix reporting of required artifact check in dry-run mode

---

src/artifact_providers/base.ts
src/artifact_providers/none.ts
src/artifact_providers/zeus.ts
src/commands/artifacts_cmds/download.ts
src/commands/artifacts_cmds/list.ts
src/commands/publish.ts

Currently, all of the `listArtifactsForRevision` methods on artifact providers (the base and its descendants) have a signature indicating that they return one of three things: an array full of artifacts, an empty array, or `undefined`. The reason for this is historical, as these three possible return values correspond to the three possible responses when asking zeus for a commit's artifacts, respectively
1. "Yup, got that commit, and here are the associated artifacts."
2. "Yup, got that commit, but there are no artifacts associated with it."
3. "Wait, what commit do you want stuff for? Never heard of it."
The only reason response number two is a possibility, though, is because zeus is both a status provider _and_ an artifact provider, the former role being the one which would let it learn …

ref(zeus): Make zeus handle its own special cases

---

src/__mocks__/logger.ts
src/artifact_providers/base.ts
src/artifact_providers/gcs.ts
src/artifact_providers/zeus.ts
src/commands/publish.ts
src/config.ts
src/targets/gcs.ts
src/utils/__fixtures__/gcsApi.ts
src/utils/__fixtures__/gcsFileObj.ts
src/utils/__tests__/gcsAPI.test.ts
src/utils/gcsApi.ts

Adds another option besides zeus for artifact storage.
Things happening in this PR (commits should be relatively self-contained) :
- All config provided to artifact constructors is now passed in a `config` object, which is then stored on the provider instance. This config now also includes any options specified for the artifact provider in the project config file.
- New `GCSArtifactProvider` class, implementing artifact listing and downloading (and underlying methods implemented in GCS client).
- Fix for GCS creds env variable name, which didn't match README.
- Tests for new GCS client methods. Includes pulling fixtures and the logger mock each into their own file.
Things to happen in further PRs:
- General clean up of code and logging associated with the above changes.
- Creation of an …

feat(artifacts): Implement GCS artifact provider

---

CHANGELOG.md
src/targets/cocoapods.ts

We do not need to fetch the `COCOAPODS_TRUNK_TOKEN` from the env.
People should call `pod trunk register` themselves if they are allowed to publish the package. Cocoapods then will grab the auth credentials correctly.

ref: Remove cocoapods token requirement

---

src/utils/__tests__/gcsAPI.test.ts
src/utils/gcsApi.ts
yarn.lock

According to the GCS docs ([1](https://googleapis.dev/nodejs/storage/latest/global.html#UploadOptions) and [2](https://cloud.google.com/storage/docs/json_api/v1/objects/insert#request_properties_JSON)), `contentType` is an attribute _inside of_ (rather than as a sibling to) `metadata` in the `UploadOptions` object. However, if you do put it in the wrong place, it appears that the underlying GCS library tries to be clever, and moves it for you... thereby mutating an object (in this case, `DEFAULT_UPLOAD_METADATA`) whose value would otherwise never change. As a result of that mutation, the `contentType` value from one file can leak into the upload options for other files, causing incorrect content types.
This PR fixes that by 1) including `contentType` in the right spot, an 2) cloning the …

fix(GCS): Fix location of `contentType` upload option

---

src/targets/__tests__/crates.test.ts
src/targets/crates.ts

Crates can be prevented from publishing by setting `publish=false` in Cargo.toml. The cargo metadata command then returns an empty list in the `publish` key, instead of `null`. This can be used to detect such crates and skip them during the publish stage.
Fixes #80

fix(crates): Skip crates with publish=false

---

CHANGELOG.md
src/commands/prepare.ts

Fixes https://github.com/getsentry/craft/issues/75
Tested locally, console output:
```
➜ node ~/Projects/craft/dist/index.js prepare 3.5.1 --no-git-checks
ℹ info craft 0.9.4
ℹ info "craft" version is compatible with the minimal version from the configuration file.
⚠ warn Not checking the status of the local repository
⚠ warn Not checking if the version (git tag) already exists
ℹ info Changelog policy is set to "none", nothing to do.
ℹ info Preparing to release the version: 3.5.1
<-- console.log -->
null
<-- console.log -->
ℹ info Created a new release branch: "release/3.5.1"
ℹ info Switched to branch "release/3.5.1"
⚠ warn Not running the pre-release command: no command specified
ℹ info Not commiting anything since preReleaseCommand is empty.
ℹ info Pushing the release branch …
```

fix: Use git show-ref over error code parsing

---

CHANGELOG.md
src/targets/cocoapods.ts

The cocoapods target always fails because we have some silly warning we can't get rid of.
This results in `craft publish` command never going through.
```
pod: [!] The spec did not pass validation, due to 7 warnings (but you can use `--allow-warnings` to ignore them).
pod:
```
This adds `--allow-warnings` by default so craft doesn't fail.
I know not 100% nice but I am trying to be pragmatic and save time on every release.

feat: Add allow-warnings to cocoapods target

---

README.md
src/commands/prepare.ts
src/commands/publish.ts
src/config.ts
src/schemas/projectConfig.schema.ts
src/schemas/project_config.ts

This adds a new config parameter to override the branch name prefix used for release branches. Docs state:
> This overrides the prefix for the release branch name. The full branch name used for a release is `{releaseBranchPrefix}/{version}`. The prefix defaults to `"release"`.
>
> ```yaml
> releaseBranchPrefix: publish
> ```

feat(config): Add a releaseBranchName config attribute

---

README.md

For scoped npm packages (ones which are `@orgname/package` or `@username/package` rather than just `package`), the default is to [publish them privately](https://docs.npmjs.com/creating-and-publishing-scoped-public-packages#publishing-scoped-public-packages):
In our `npm` target config, we allow the user to specify a value for the `access` flag, in order to be able to publish scoped packages publicly:
However, in spite of the fact that we say that the default is `public`, nowhere do we actually set that default. Therefore, we fall back to the `npm publish` default, which is private.
(This hasn't been as apparent because once a package is published once (either publicly or privately), the access setting won't change unless you use a [different …

fix(docs): Fix npm `access` config option having wrong default

---

.craft.yml
CHANGELOG.md
README.md
src/commands/prepare.ts
src/schemas/projectConfig.schema.ts
src/schemas/project_config.ts
src/utils/__tests__/changes.test.ts
src/utils/changes.ts

This patch adds the "auto" changeset policy, which works as follows:
1. If there is already a changeset entry for the new version, use that (same as simple)
2. Else if there is an "Unreleased" changeset, rename that to the new version
3. Else, create a new version section with a default text
~~4. In all cases, create an empty "Unreleased" section at the top~~
Decided to remove the creation of an empty "Unreleased" section as that would end up in the final commit/tag which is pointless: you don't expect to see an "unreleased" section on your version commit/tag.
TODO:
1. ~~Add tests~~
2. Make "Unreleased title" configurable (follow up)
3. ~~Respect existing changelog files indentation and header style~~
4. Add a bunch more tests for `prepare` command, especially for dry run (follow up)

feat(changelog): Add "auto" changeset policy

---

CHANGELOG.md
action.yml

Moves the definition from [getsentry/craft-action](https://github.com/getsentry/craft-action) to here.
See https://github.com/getsentry/onpremise/blob/master/.github/workflows/release.yml for an example use.

feat(gha): Add GitHub Action for Craft

---

Dockerfile
README.md
cloudbuild.yaml
src/schemas/projectConfig.schema.ts
src/targets/__tests__/crates.test.ts
src/targets/crates.ts

Cargo does not allow to publish crates with circular dependencies. In dev dependencies, they would theoretically be fine since they are not required to run or build the crate. We need them in the Rust SDK to provide proper doc comments in sub-crates. 
This PR adds a new `noDevDeps` option, which uses `cargo hack` to strip dev dependencies before publishing.

feat(crates): Add noDevDeps option

---

.eslintrc.js
CHANGELOG.md
src/artifact_providers/base.ts
src/commands/artifacts.ts
src/commands/artifacts_cmds/download.ts
src/commands/prepare.ts
src/commands/publish.ts
src/config.ts
src/logger.ts
src/status_providers/github.ts
src/status_providers/zeus.ts
src/targets/brew.ts
src/targets/cocoapods.ts
src/targets/crates.ts
src/targets/docker.ts
src/targets/ghPages.ts
src/targets/github.ts
src/targets/npm.ts
src/targets/nuget.ts
src/targets/pypi.ts
src/targets/registry.ts
src/utils/async.ts
src/utils/errors.ts
src/utils/objects.ts
src/utils/strings.ts
src/utils/system.ts

This PR continues from https://github.com/getsentry/craft/pull/113 and aims to reduce all the eslint related warnings to 0.
269aef6 has the changes related to fixing `@typescript-eslint/no-unused-vars`
See: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md
- I added `{ argsIgnorePattern: '^_' }` to make sure that variables that start with `_` were fine to be unused, as this seems to be a pattern in the code base
- Caught some unnecessary imports of lodash though!
8539795 has the changes related to fixing `@typescript-eslint/explicit-module-boundary-types`
See: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md
- This was mostly just …

fix(eslint): Address eslint warnings

---

CHANGELOG.md
src/status_providers/github.ts

When the check suites are queued but the check runs haven't started yet, Craft immediately fails. With this patch, it also checks the Check Suites API to see if there are any pending check suites.
Fixes #111.

fix(github): Don't fail when there are queued check suites

---

CHANGELOG.md
README.md
src/targets/gem.ts
src/targets/index.ts

I successfully did released https://github.com/getsentry/raven-ruby/releases/tag/3.0.2 with this branch.
```
➜ node ~/Projects/craft/dist/index.js publish 3.0.2
ℹ info craft 0.10.1
ℹ info "craft" version is compatible with the minimal version from the configuration file.
ℹ info Publishing version: "3.0.2"
ℹ info Using "GithubStatusProvider" for status checks
ℹ info Using "ZeusArtifactProvider" for artifacts
ℹ info No config provided for Github status provider, calculating the combined status...
ℹ info Revision df427b7320d36f30975d6746f730b1d12316bbf6 has been built successfully.
ℹ info
ℹ info Available artifacts:
┌────────────────────────┬─────────┬──────────────────────────────────┬─────────────────────┐
│ File Name              │ Size    │ Updated                          │ ContentType …
```

feat: Add gem target

---

CHANGELOG.md
src/status_providers/github.ts

When GitHub Actions runs are skipped based on a condition, the status check
conclusion reports `skipped`. This is currently detected as a failed status
check by craft, where instead it should be considered successful.
A use case of this is to skip certain status checks based on the kind of a release.
GitHub always reports all status checks and then marks them as skipped. See:
https://github.com/getsentry/relay/runs/1142527273

fix(github): Detect skipped status checks as successful

---

CHANGELOG.md
README.md
src/targets/docker.ts

These options became necessary for us to be able to publish Py2 and Py3 versions of Sentry images at the same time, in the same release.

feat(docker): Add sourceFormat & targetFormat options

---

README.md
src/targets/docker.ts

Addresses the review feedback on https://github.com/getsentry/craft/pull/125#discussion_r501202588

fix(docker): Use consistent names in targetFormat

---

README.md
src/targets/docker.ts

We used Mustache templates that were already available for image name formatting. Musache escapes all HTML-unsafe characters by default which rightly confused the Docker CLI client. This patch uses the `{{{varName}}}` pattern for the default format config to disable escaping.

fix(docker): Disable HTML escaping in image names by default

---

CHANGELOG.md
src/commands/publish.ts
src/schemas/projectConfig.schema.ts
src/schemas/project_config.ts

Craft allows using multiple instances of the same target with different (or same!) configurations but it assumes `name` field is a unique identifier. This PR adds an optional `id` field to distinguish multiple targets with the same name such as multiple Docker images to publish.

feat(targets): Add optional `id` field to target config

---

CHANGELOG.md
src/targets/npm.ts

The current version relied on `.npmrc` being set on the machine manually. With this change, we read the NPM_TOKEN env variable and append it to the `--registry` option we already set as suggested on https://blog.npmjs.org/post/118393368555/deploying-with-npm-private-modules

fix(npm): Actually use NPM_TOKEN for publishing

---

README.md
src/artifact_providers/github.ts
src/commands/publish.ts
src/config.ts
src/schemas/projectConfig.schema.ts
src/schemas/project_config.ts
src/targets/npm.ts
src/utils/files.ts

aka. we can kill Zeus
You need to use Github actions to upload your artifacts, here is one example from the JS repo:
```yaml
job_artifacts:
name: Artifacts Upload
needs: job_build
runs-on: ubuntu-latest
if: "contains(github.ref, 'release/')"
steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v1
- uses: actions/cache@v2
with:
path: |
${{ github.workspace }}/node_modules
${{ github.workspace }}/packages/**/node_modules
${{ github.workspace }}/packages/**/build
${{ github.workspace }}/packages/**/dist
${{ github.workspace }}/packages/**/esm
key: ${{ runner.os }}-${{ github.sha }}
- name: Pack
run: yarn pack:changed
- name: Archive Artifacts
uses: actions/upload-artifact@v2
with:
name: ${{ github.sha }}
path: |
${{ github.workspace }}/packages/browser/build/**
${{ github.workspace …
```

feat: Github Artifact Provider

---

src/targets/npm.ts

`npm publish` is not able to receive a `--registry=` argument and therefore ignores it see: https://docs.npmjs.com/cli/v6/commands/npm-publish
Someone who wants to publish needs to have something in their local `~/.npmrc` file which npm fills when calling `npm login`
I am not sure how to work around this but depending on `NPM_TOKEN` being in the `process.env` doesn't work.
I also tried it having no `.npmrc` file, no success.

fix: remove npm token usage

---

CHANGELOG.md
src/commands/publish.ts
src/targets/index.ts

With this patch, only targets defined in `.craft.yml` are accepted
in the `-t` flag, also fixing #136.
<pre>
craft publish --help
i info craft 0.13.2
dist publish NEW-VERSION
🛫 Publish artifacts
Positionals:
NEW-VERSION  Version to publish                            [string] [required]
Options:
--no-input         Suppresses all user prompts      [boolean] [default: false]
--dry-run          Dry run mode: do not perform any real actions
[boolean] [default: false]
--target, -t       Publish to this target
[string] <b>[choices: "npm", "gh-pages", "gcs", "registry", "github",
"docker[release]", "docker[latest]", "all", "none"] [default: "all"]</b>
--rev, -r          Source revision (git SHA or tag) to publish (if not release
branch head)                                       [string] …

fix(publish): Only allow valid target ids for -t

---

README.md

DockerHub now requires to use personal access tokens instead of passwords for
API access.

doc(docker): Mention access token instead of password

---

src/targets/npm.ts

This is a retake on #130. Although npm/cli#8 claims to have support
for `npm_config_//registry.npmjs.org/:_authToken=` usage, my tests
and the reports on the internet says this still doesn't work, even
with the latest npm (7.0.15 at the time).
The only way to pass the token is to have the `authToken` line in
an `.npmrc` file. The quick&dirty way would have been to create one
in the project directory but that may collide with a potentially
pre-existing project `.npmrc`. Trying to merge these seems more
trouble than it is worth:
https://github.com/actions/setup-node/blob/59e61b89511ed136a0b17773f07c349fa5c01e8b/src/authutil.ts
(even worse as you'd need to revert these changes after the fact)
The "better" solution I found is:
1. Create a temporary file as your npmrc
2. Put the token/registry …

fix(npm): Fix NPM_TOKEN usage again

---

CHANGELOG.md
README.md
src/commands/__tests__/publish.test.ts
src/commands/publish.ts
src/schemas/projectConfig.schema.ts
src/schemas/project_config.ts

This PR adds an optional post-release script which is needed for
projects like [getsentry/sentry](https://git.io/JIs4n) and
[getsentry/onpremise](https://git.io/JIs4l). This would help keeping
the common publish/release repo and its downstream project independent.

feat(publish): Add optional post-release script

---

.github/workflows/release.yml

Follow up/fix to #129 as we separated the publish step now.

ci(release): We don't need a special things for checkout

---

.github/workflows/release.yml

This essentially reverts commit 8aab991e96c929285d9de5048d21efa74d211e0f.
Reason is GitHub preventing triggering more actions form inside another
action using the default `GITHUB_TOKEN`:
- https://stackoverflow.com/a/64078507/90297
- https://github.community/t/push-from-action-does-not-trigger-subsequent-action/16854

ci(release): Add GH_RELEASE_PAT as we need a PAT to trigger builds

---

README.md

docs(npm): Add missing `NPM_TOKEN` env var requirement

---

CHANGELOG.md
src/targets/github.ts

Fixes `publish` failing when running in dry-run mode as it skips creating a release but then tries to find the existing assents on that release. Since the release is not there, it was failing with a 404. This PR skips this step entirely in dry-run mode.

fix(publish): Fix fail on dry-run w/ github target

---

CHANGELOG.md
README.md
action.yml
src/utils/githubApi.ts

This PR adds support for `GITHUB_TOKEN` env variable and prefers that over the old `GITHUB_API_TOKEN` without dropping support for the old one.

ref(github): GitHub standardized on GITHUB_TOKEN so let's use that

---

src/utils/__tests__/version.test.ts

Hello. I've add some test cases for 'versions'.
- Empty string
- Ignore values following after 'patch'
Please check 🙏

Add tests for 'version'

---

package.json
yarn.lock

This is to upgrade the vulnerable `axios` dependency. The latest version has the following breaking changes which are all okay:
- automatically detect contentType if not provided (googleapis/nodejs-storage#1190)
- drop keepAcl parameter in file copy (googleapis/nodejs-storage#1166)
- drop support for node.js 8.x
- allow leading slashes in file name (googleapis/nodejs-storage#820)
- upgrade engines field to >=8.10.0 (googleapis/nodejs-storage#688)

upgrade(@google-cloud/storage): ^5.7.0

---

.github/workflows/release.yml

Stats utilizing the latest niceties in getsentry/action-prepare-release#4.
#skip-changelog

ci(release): Move on to the improved action-prepare-release version

---

package.json
src/artifact_providers/base.ts
src/artifact_providers/github.ts
src/status_providers/base.ts
src/utils/__tests__/changes.test.ts
yarn.lock

Upgrades Typescript version to the latest currently available. This upgrade is a requirement in order to use the AWS SDK v3.

ref: Upgrade Typescript to latest (^4.1.3)

---

CHANGELOG.md
src/utils/__fixtures__/gcsApi.ts
src/utils/__tests__/gcsAPI.test.ts
src/utils/gcsApi.ts

Ideally we should fix all the Craft configs to not have this leading slash but that's hard and is also a breaking change so we normalize this ourselves like old times. Fixes #169.

fix(gcs-target): Fix incorrect upload path to GCS when it has a leading slash

---

.craft.yml
CHANGELOG.md

Changes the changelog policy to "auto" and updates the latest version of the changelog to "Unreleased"

meta: Changelog policty to "auto"

---

CHANGELOG.md
src/targets/registry.ts

Fixes an issue where symlinks could not be created, since there's the `versionFilePath` string instead of the actual version file path.

fix: Replace actual versionFilePath

---

CHANGELOG.md
src/targets/registry.ts
src/utils/checksum.ts

Fixes https://github.com/getsentry/sentry-docs/pull/3024

fix: `undefined` handling when there's no `checksums` in `.craft.yml`

---

package.json
src/utils/githubApi.ts
yarn.lock

This version has a minor breaking change. I wanted to upgrade it before working on expanding retries on `404` responses to alleviate GitHub being slow on making artifacts ready.

upgrade(octokit/retry): Upgrade @octokit/retry to its latest version

---

CHANGELOG.md
src/utils/githubApi.ts

Allows retries on `404` responses from GitHub as their API may lag occassionally when making artifacts or check runs available.

feat(github): Retry on 404s

---

CHANGELOG.md
src/targets/awsLambdaLayer.ts
src/utils/awsLambdaLayerManager.ts

AWS regions are requested using the EC2 client, and Lambda layers are published to these regions using the Lambda client. However, it may be possible that an exception is raised (such as a timeout exception). With this PR these exceptions are catched and warned, without stopping Craft. Note that even if there's an exception, layers may be created.

ref(aws-lambda): Catch potential exceptions when publishing AWS Lambda layers to new regions

---

CHANGELOG.md
src/targets/awsLambdaLayer.ts

Craft can create AWS Lambda layers for multiple runtimes. This PR adds the runtime names in the commit message, instead of just having the version.

feat(aws-lambda): Add runtime names on commit message

---

CHANGELOG.md
src/utils/__tests__/packagePath.test.ts
src/utils/packagePath.ts

Companion to https://github.com/getsentry/sentry-release-registry/pull/45
We decided to allow colons as canonical name separators, in addition to slashes.

feat(registry): Allow colons as separators in canonical names

---

CHANGELOG.md

Ideally we should allow the original too, but let's unblock the release for now.
Without it, craft doesn't process this changelog properly.

fix(changelog): Update unreleased marker

---

CHANGELOG.md
src/targets/registry.ts

fix(registry): Ensure up-to-date remote before pushing

---

CHANGELOG.md
src/targets/registry.ts

Passes `--rebase` as option, instead of a literal `rebase` which git interprets as a remote. Additionally, I'm opting for the array-based syntax as it's more concise and in line with other git invocations in the same file. See [how to specify options](https://www.npmjs.com/package/simple-git#how-to-specify-options).
Disclaimer: I did not test this branch. Please test before merging.

fix(registry): Specify correct rebase flag

---

src/artifact_providers/github.ts

GitHub sometimes takes a few minutes until it lists freshly uploaded artifacts on its API. This PR adds a retry mechanism when we cannot find any artifacts for the given revision. It also improves the pagination mechanism to no scan artifacts beyond the revision's commit date to shorten lookup times.
Fixes #182.

fix(github-artifacts): Better pagination and retry on missing artifacts

---

README.md

@BYK Was kind enough to help me understand Craft a little better, we ended up with this doc improvement.

docs: Expand descriptions of `craft {prepare,publish}`

---

CHANGELOG.md
src/commands/publish.ts

This is a follow up to #192. It fixes a bug that occurs when a
publish state file does not list all possible targets. In this case
any unlisted target, is skipped whereas its state should be treated
as "unpublished". This stemmed from a logic error in the if statement
which skipped publishing when the special target type "none" was passed.
The PR also refactors the code around this a bit to make it easier
to follow and less prone to errors. Ideal follow ups would be more
tests around publish and the state file functionality.
Example case: https://github.com/getsentry/publish/runs/2254551314?check_suite_focus=true#step:8:45
When it found a state file, Craft completely skipped the whole publish pipeline, causing the `github` target to not be published but the publish operation successfully …

fix(publish): Fix publishing when resuming from a state file

---

CHANGELOG.md
src/artifact_providers/github.ts
src/commands/prepare.ts
src/commands/publish.ts
src/index.ts
src/status_providers/github.ts

Our default info level logging is a bit too noisy and outputs redundant information that would only be useful when debugging. This also caused issues withe the new `targets` command on CI as we were always outputting `[no-input]` when we detected CI. This PR moves most of these messages to debug level.

ref(logger): Move some extra info to debug level

---

CHANGELOG.md
src/utils/githubApi.ts

This PR reverts #177 as not only it did not address the issue it
was intending to fix, it introduced delays in where we actually
expect a 404 response. It also caused a weird failure where we
threw an error due to a 404 response which should have been ignored:
https://github.com/getsentry/publish/runs/2281793805?check_suite_focus=true#step:8:59
The retry issue was resolved via #190.

fix(github): Revert retry on 404s

---

CHANGELOG.md
src/utils/gcsApi.ts

Use `path.posix` instead of `path` when generating the `prefix` for GCS file listing so Craft works as expected on Windows too.

fix(gcs): Fix GCS artifact provider on Windows

---

CHANGELOG.md
README.md
src/commands/prepare.ts
src/config.ts

This PR switches default artifact and status providers to GitHub if the minimum required Craft version is set to 0.21.0 or above. This is *not* a breaking change for older projects.

feat(config): Use GitHub as default provider

---

CHANGELOG.md
package.json

With the single-file builds now being used for npm package too, we do not have any non-dev dependencies. This PR fixes that so when you do `npm install craft` it doesn't download any dependencies, just craft

fix: No prod dependencies

---

.craft.yml

This PR removes the redundant `artifactProvider` and `statusProvider` configs with Craft 0.21.0. It also reorders publish targets for importance and priority.

ci: Update Craft config for 0.21.0

---

.github/workflows/build.yml
CHANGELOG.md
package.json

We were not setting the node version on CI build matrix which means we were just testing everything with Node 12 but twice. This patch fixes that, adds Node 14 & 16 to the build matrix, switches our artifact builds to be on the 'blessed' Node and Yarn versions defined in our package.json `volta` config, and bumps Yarn and Node to their latest versions without breaking changes.

ci: Fix our build matrix, add Node 14 & 16

---

CHANGELOG.md
jest.config.js
src/utils/__tests__/strings.test.ts
tsconfig.build.json
tsconfig.json

Our Jest and TS configs were a bit convoluted and since our TS config was based off of a web-based base config, it was building for browsers and was shipping/adding DOM-related things into our builds. This even uncovered a bug in our tests which is fixed with this patch.

build: Fix and simplify jest and TS configs

---

README.md
src/targets/__tests__/upm.test.ts
src/targets/github.ts
src/targets/index.ts
src/targets/upm.ts

Unity SDK works in two repositories:
https://github.com/getsentry/sentry-unity <- SDK
https://github.com/getsentry/unity <- release repo for the user
Unity users add our package by providing a git URL to their package manager. Versioning and potential rollbacks for them are made available via tags (i.e. https://github.com/getsentry/unity.git#x.x.x).
Release steps:
1. Get the prepared artifact (a single .zip containing the package)
2. Pull the release repository
3. Replace everything in that repo with the contents of the .zip
4. Update tag & push

feat: Add upm target

---

CHANGELOG.md
README.md
src/config.ts
src/schemas/projectConfig.schema.ts
src/schemas/project_config.ts
src/targets/github.ts

In monorepos like getsentry/sentry-ruby, Craft cannot determine and fetch the remote changelog because it assumes `.craft.yml` is always at git root. This patch adds this optional config and automatically fills it when a `.git` root is found so we can have changelogs in monorepos.
This is to fix https://github.com/getsentry/sentry-ruby/pull/1435#issuecomment-834465195

feat: Add projectPath config option to GitHub

---

CHANGELOG.md
src/artifact_providers/github.ts
src/artifact_providers/zeus.ts

For some reason we did not allow more than one artifact tied to a commit SHA (which may happen with branches etc). Now we allow this and pick the most recent one.

fix(github-artifacts): Allow multiple artifacts on the SHA, use latest

---

src/artifact_providers/base.ts
src/artifact_providers/gcs.ts
src/artifact_providers/github.ts
src/artifact_providers/none.ts
src/artifact_providers/zeus.ts
src/commands/publish.ts
src/status_providers/base.ts
src/status_providers/github.ts
src/status_providers/zeus.ts

Since the single-file builds, we started to see log lines such as `Got status "success" from status provider: Vae`. This is because we minify the output, which changes function/class names for optimization and these lines rely on this `constructor.name` property. This patch adds explicit names to avoid using the `--keep-names` option in `esbuild` as that adds ~300kiB to the final file size just for this minor issue. This patch however is weightless*.

fix(debug): Fix mangled provider names on debug/info logging

---

package.json
src/commands/prepare.ts
src/index.ts
yarn.lock

Since we used 'strict mode' in `yargs` and then enabled mapping of _any_ `CRAFT_*` env variables to CLI args, Craft now complains when it sees env variables like `CRAFT_GCS_STORE_CREDS_JSON` which are only directly used from specific targets and not available through the CLI. In an ideal world, either these wouldn't start with the `CRAFT_` prefix, or would be available as CLI args. Since we are not in that world, we are doing a compromise: converting one simple thing we acn into a CLI arg, and then relaxing the strictness by only being strict about the commands but not options. Since this feature (`strictCommands()` was added in a later version, we also upgrade `yargs` to `15.4.1` which is the canonical version being used by other tools in the repo.
Fix up to #224.

fix(cli): Allow extra CRAFT_* env variables

---

action.yml

Since now we can pass all CLI flags via `CRAFT_` env variables, we can remove the broken arguments construct from the GitHub action and remove these inputs.

fix(action): Remove weird input options for publish

---

CHANGELOG.md
src/index.ts

This fixes the release failures such as https://github.com/getsentry/sentry/runs/2591288014?check_suite_focus=true.
The culprit is #224 where we switched the global `--no-input` and
`--dry-run` flags from boolean to string args.
This now causes  `craft prepare --no-input "21.5.0"` to be interpreted
as `craft prepare --no-input=21.5.0`.
This patch fixes the issue.

fix(cli): Fix global flag parsing interference

---

CHANGELOG.md
src/artifact_providers/base.ts
src/artifact_providers/github.ts
src/artifact_providers/zeus.ts
src/logger.ts
src/targets/awsLambdaLayer.ts
src/targets/base.ts
src/targets/brew.ts
src/targets/cocoapods.ts
src/targets/crates.ts
src/targets/docker.ts
src/targets/gcs.ts
src/targets/gem.ts
src/targets/ghPages.ts
src/targets/github.ts
src/targets/npm.ts
src/targets/nuget.ts
src/targets/pypi.ts
src/targets/registry.ts
src/targets/upm.ts
src/utils/awsLambdaLayerManager.ts
src/utils/gcsApi.ts
src/utils/helpers.ts

After the `consola` upgrade in #224, we stopped respecting the log level that is set further in execution in scoped logger which were created eagerly at module initialization time and not inheriting the log level that was changed afterwards. This patch moves these module-level loggers into base class constructors and standardizes them. This both fixes the issue and gives a common logging style for all artifact providers and targets.

fix(logging): Fix scoped loggers not respecting log level

---

CHANGELOG.md
src/artifact_providers/__tests__/github.test.ts
src/artifact_providers/github.ts
src/utils/__tests__/githubApi.test.ts

Fixes #234. This is a follow up to #226. Although @chadwhitacre pointed out a logic issue in an earlier revision, we have failed to see that we were _always_ returning an artifact even if we don't have a proper name match as `reduce` without an initial value, starts with the first element of the array. This patch fixes the issue.

fix(github-artifacts): Fix incorrect artifact resolution

---

CHANGELOG.md
src/artifact_providers/__tests__/github.test.ts
src/artifact_providers/base.ts
src/artifact_providers/gcs.ts
src/artifact_providers/github.ts
src/artifact_providers/none.ts
src/artifact_providers/zeus.ts
src/commands/publish.ts
src/config.ts
src/logger.ts
src/status_providers/base.ts
src/status_providers/github.ts
src/status_providers/zeus.ts
src/targets/base.ts
src/targets/github.ts

When looking at https://github.com/getsentry/publish/runs/2682656771?check_suite_focus=true#step:8:28
I noticed there were 2 issues with our logging:
1. The scope name was not correct (base vs github)
2. The logging level for the scoped logger was incorrect (debug vs info)
Issue no 1 stems from a quirk in ES6 classes where property initializers
are not run until after the `super()` call
which sets up the logging, failing to pick up the new `name` set in the
inherited class.
Issue no 2 stems from `Consola`'s `withScope` method not inheriting or
cascading the parent logging level to the new, scoped loggers.
This PR solves both issues.

fix(logging): Proper scoping and log levels

---

src/artifact_providers/github.ts
src/commands/prepare.ts
src/commands/publish.ts
src/status_providers/github.ts
src/targets/awsLambdaLayer.ts
src/targets/brew.ts
src/targets/gcs.ts
src/targets/github.ts
src/targets/upm.ts
src/utils/__tests__/env.test.ts
src/utils/env.ts
src/utils/files.ts
src/utils/gcsApi.ts
src/utils/helpers.ts
src/utils/registry.ts
src/utils/system.ts

We are planning to set logging level to `Debug` over at `getsentry/publish` but it tends to be too noisy. This PR goes over all `logger.debug()` calls, tidies them up, and moves some of them to `logger.trace()` level to make debug-logging more usable.

ref(logging): Overhaul debug level logging

---

CHANGELOG.md
src/utils/git.ts

When we query for the default branch, we assume `origin/HEAD` exists. That said this ref is only set and needed when you clone a repo and GitHub's `action/checkout` seems to be doing something weird that doesn't set this, causing issues like https://github.com/getsentry/sentry-javascript/runs/2730108174?check_suite_focus=true#step:3:10. This patch should fix the issue.

fix(git): Ensure origin/HEAD is set

---

CHANGELOG.md
package.json
yarn.lock

Forces parse-url to be >=5.0.3 to rectify the security vulnerability in `normalize-url`, which was used by earlier versions.

upgrade(parse-url): Force parse-url>=5.0.3 for security

---

CHANGELOG.md
src/targets/registry.ts

Follow up to #259.
Fixes the `Cannot read property 'onlyIfPresent' of null` error
when using the new batch config for registry in without extra
config.
See
https://github.com/getsentry/publish/runs/2841903865?check_suite_focus=true#step:8:83
Unblocks getsentry/publish#400

fix(registry): Fix error w/ simple registry config

---

src/targets/symbolCollector.ts

Be verbose on the output of the symbol collector call.

ref(symbol-collector): Verbose output of command

---

Dockerfile

Updating Symbol Collector to take the latest bug fixes: https://github.com/getsentry/symbol-collector/releases/tag/1.3.2 that affect the CLI used by craft

fix(docker) symbol collector bump 1.3.2

---

CHANGELOG.md
src/targets/__tests__/maven.test.ts
src/targets/maven.ts

Add support for BOM files in the `maven` target.
This is based on [previous Kotlin code](https://github.com/getsentry/sentry-java/blob/bf425d511746782ee51a9ac475fa353997d6f34e/scripts/release.kts), but that's incomplete. A BOM file is a POM file with a `<packaging>pom</packaging>` key.
An artifact (the `zip` downloaded from GHA) may contain a POM and a BOM, both with the same name (`pom-default.xml` is the default name). In case both are present, unzipping the artifact may lead to having an unknown name for the BOM file (e.g. the POM is the `pom-default.xml`, and the BOM is ??). Thus, if the default file isn't a BOM, all `xml` files in the artifact are checked to not miss the BOM. If no BOM is found, the distribution is uploaded as it is now (without this PR); and if a BOM is found, a …

ref(maven): Support BOM files in `maven` target

---

CHANGELOG.md
src/targets/__tests__/maven.test.ts
src/targets/maven.ts

Removing the `gradle.properties` after running the maven target may prevent exposing it, which contains the OSSRH credentials (see https://github.com/getsentry/craft/issues/272). There also are minor changes to address some feedback in https://github.com/getsentry/craft/pull/270.

feat(maven): Remove Gradle properties after publishing

---

README.md
src/targets/__tests__/maven.test.ts
src/targets/maven.ts

- Don't log when not finding BOMs. Most of the packages aren't supposed to be BOM files, and logging this may give the impression that something is missing when it's not.
- Add a note to the target's docs to show command output when the log level is `trace`.

ref(maven): Improve logging for `maven` target

---

src/artifact_providers/__tests__/base.test.ts
src/targets/__tests__/symbolCollector.test.ts
src/targets/symbolCollector.ts

- Clean up tests for the base artifact provider.
- Add tests to cover more edge-cases, such as having strings, regex, and undefined on the same call.
- Other minor changes.

test(symcollector): Add tests for filter options

---

CHANGELOG.md
README.md
src/targets/__tests__/maven.test.ts
src/targets/maven.ts

The `maven` target is responsible for releases related to Maven. Currently, the Android configuration is required, but there are scenarios where it isn't used (e.g. https://github.com/getsentry/sentry-android-gradle-plugin). This PR makes the android configuration optional.

feat(maven): Optional `android` config

---

CHANGELOG.md
Dockerfile

upgrade(docker): Upgrade to Debain Bullseye and Node 14

---

scripts/bump-version.sh
src/commands/__tests__/prepare.test.ts
src/commands/prepare.ts
src/utils/git.ts

With this patch, we do a crude determination of the previous release,
assuming the first tag before current tip  the previous release.
This is rather naive as we allow custom formatting of git tags but it is
a good start nevertheless.

feat(prepare): Pass old version to bump-version

---

src/commands/publish.ts
src/utils/errors.ts

TypeScript now defaults to `unknown` for caught error types instead of `any` causing us to get warnings when trying to access some standard `Error` properties. This PR changes the code accordingly so it is both safer, cleaner, and does not have this warning anymore.

ref: Fix TypeScript type warning regarding catch

---

src/utils/git.ts

ref: Add comments for changelog extraction

---

package.json
src/artifact_providers/__tests__/github.test.ts
src/artifact_providers/github.ts
src/status_providers/github.ts
src/targets/awsLambdaLayer.ts
src/targets/brew.ts
src/targets/cocoapods.ts
src/targets/ghPages.ts
src/targets/github.ts
src/targets/registry.ts
src/targets/upm.ts
src/utils/__tests__/githubApi.test.ts
src/utils/githubApi.ts
yarn.lock

This is needed so we can use the GraphQL endpoints.
List of breaking changes: https://github.com/octokit/rest.js/releases/tag/v18.0.0
All tests pass and also manually verified locally by preparing and releasing https://github.com/getsentry/release-tester/releases/0.18.0

upgrade(octokit): Upgrade octokit to v18

---

CHANGELOG.md
src/utils/__tests__/changelog.test.ts
src/utils/changelog.ts

In #291 we used level 2 headers for subsections in the auto
generated changelogs. This made them collide with the level 2
version headers, causing our GitHub target to not pick up the
automatically generated changelog. It is also semantically
incorrect.
This patch fixes the issue, introduces constants to determine
these levels, and adds a helper function that utilizes these
constants.

fix(changelog): Make auto changelog titles level 3

---

src/utils/__tests__/changelog.test.ts
src/utils/changelog.ts

We need to escape the `#` sign in milestone titles and bodies as it may interfere or get hidden with the markdown formatting (it uses `#` to identify headers). This patch fixes the issue and it also fixes another issue when the milestone description was empty.

fix(changelog): Escape # in milestones

---

src/utils/__tests__/changelog.test.ts
src/utils/changelog.ts
src/utils/git.ts

We sometimes want to omit certain changes (such as internal changes in Relay and this patch brings the option to skip them from the changelog altogether.

feat(changelog): Skip items with `#skip-changelog` in them

---

package.json
yarn.lock

This is to address [CVE-2021-3807](https://github.com/advisories/GHSA-93q8-gq69-wqmw)
The only breaking changes from version `2.1.1` to `5.0.1` were supported Node versions so I forced all of them to `5.0.1`. Avoided `6.0.1` as it converted the package into ESM which I'm not sure if we are ready for yet.

upgrade(ansi-regex): Upgrade ansi-regex to 5.0.1

---

src/utils/__tests__/changelog.test.ts
src/utils/changelog.ts

While testing this on Sentry, we came by some milestones where their `description` field was `null`. This does not happen with new milestones but we still need to cover for that case to avoid crashes.

fix(changelog): Accomodate `null` milestone descriptions

---

src/targets/github.ts

The upload requires binary data not strings.  Unfortunately the typing
information in the generated octokit typings is wrong about this.
Passing a string here creates invalid binary uploads and has caused an
incident at Sentry that caused invalid uploads.
Octokit issue: https://github.com/octokit/octokit.js/issues/2086
Fixes https://github.com/getsentry/sentry-cli/issues/1037

fix: github release uploads

---

src/utils/files.ts

Fixes the useless and incorrect
`Couldn't remote temp dir XXX: null` error.

fix: Only log error on tempdir rm when ther is an error

---

src/targets/github.ts

We had an incident where we sent UTF-encoded string
when uploading GitHub release artifacts after an
Octokit upgrade due to misleading types. We haven't
noticed the issue until it was too late as we lack
basic checks such as file size and checksums. This
patch introduces both checks to the GitHub target.
Closes #303.

feat(github): Verify release uploads for GitHub

---

src/targets/github.ts

This is a workaround for #322, where we're finding that our checksum comparison algorithm is not always sufficient. Better to log and proceed rather than block deployment in such cases.

Relax checksum requirement

---

src/targets/github.ts
src/utils/version.ts

Was reading some code, and in passing cleaned some docs.
Notes:
- Terminate sentences with punctuation
- Github -> GitHub (but didn't change functions/methods/types in this passing, only references to the company name)

docs: Fix typos and cleanup some documentation

---

src/targets/github.ts

The GitHub API doesn't provide any endpoints to get the hash of an asset.
GitHub's response contains an ETag header with the MD5 hash of the asset.  In
certain cases, the ETag header is not present. This means we don't have the
hash of the asset, and thus, we cannot verify the asset correctness. To verify
it, we download the file and calculate the hash locally.
Files are downloaded into memory, and their size is not checked. This has a
risk of downloading too big files, which is something we accept at the moment.
The GitHub SDK throws exceptions when server responses are HTTP errors. These
interactions are wrapped and more detailed errors are thrown.
Originally, the hash check was introduced in https://github.com/getsentry/craft/pull/308.
This is a follow-up to the initial fix: …

feat(target-gh): Check asset MD5 hash by downloading the asset

---

src/targets/github.ts

When a size check fails, it was hard to tell what was the local size and
what was the uploaded size without looking at the source code.

misc: Update error message to clarify what size refers to what

---

src/targets/github.ts

Upon close inspection of the code changes introduced in 57e96687cfd80522dc5c9fb8deeac3d5583b5733, it turns out that the portion of code that compares the checksum of the local file against the uploaded file was innefective to protect against the bug introduced in c978bf605d7b4a3a6c297659e4a55f91b7a869f4.
The checksum comparison compared bytes after reading an asset file from disk, and essentially protected us from mishandling on GitHub's side, but not from reading and uploading incorrect data, specifically:
readFileSync(path, { encoding: 'binary' })
The bug was fixed in 4697dbdbecfdc6444e62b9c50bdd617829d20d18, but notice how from then on we started using `readFileSync` instead of `createReadStream` (a potential problem for large assets as we don't really need to hold all bytes in memory …

fix: Remove GitHub asset checksum

---

src/utils/__tests__/changelog.test.ts
src/utils/changelog.ts

Nobody's going to read through a list of 1,000s of commits, may as well use git log at that point.
What's more, over-long changesets can lead to [GitHub API failures](https://github.com/getsentry/self-hosted/issues/1193#issuecomment-995011767).

Limit the number of leftovers listed

---

src/targets/crates.ts

See https://github.com/getsentry/sentry-rust/issues/374#issuecomment-952669578
The initial problem is that cargo validates (dev)-dependencies before publishing, and rejects that if the required version does not exist on crates.io yet. path-only dev-dependencies skip this check, and are thus not holding up publishing.
The previous method of using `cargo-hack` and the `noDevDeps` flag should be discouraged as it uses the `--allow-dirty` flag and thus prevents cargo from putting in more metadata that could be used for crate integrity validation (aka, the code in the crate matches a git commit; which it currently does not due to usage of `cargo-hack`)
Read https://codeandbitters.com/published-crate-analysis/ for more insight into why `cargo-hack` should be avoided.

fix(crates): Skip path-only dev-dependencies in dep cycle checking

---

src/commands/prepare.ts
src/targets/github.ts
src/targets/upm.ts

Closes #336.
Tested with https://github.com/getsentry/testing-craft-chadwhitacre/blob/0.0.9/test.
E.g. https://github.com/getsentry/testing-craft-chadwhitacre/
------------
------------

Publish to GitHub more atomically using draft repos

---

src/targets/__tests__/maven.test.ts
src/targets/maven.ts

There is no `$HOME/.gradle` directory by default in our docker instance, thus writing to `$HOME/.gradle/gradle.properties` thows an error.

fix: Make sure that gradle directory exists before writing to it

---

Dockerfile

Current version is failing for some releasese, eg. https://github.com/getsentry/publish/runs/5333817295?check_suite_focus=true
ref: https://github.com/getsentry/symbol-collector/issues/124

deps: Roll back to symbol-collector 1.4.2

---

src/commands/publish.ts

This is WiP to fix https://github.com/getsentry/craft/issues/327
We remove automatic branch detection, use the default as the main source of truth, but allow for overriding it through the GH Action input (this needs to be added per repository, inside `.github/workflows/release.yml` in `with` clause).
Related required issues:
https://github.com/getsentry/action-prepare-release/pull/23
https://github.com/getsentry/publish/pull/838

ref: Use default branch as merge target instead of parent detection

---

Dockerfile

Includes fix for https://github.com/getsentry/symbol-collector/issues/124 via https://github.com/getsentry/symbol-collector/pull/125 change.

deps: Update symbol-collector to 1.5.3

---

.craft.yml
cloudbuild.yaml

Make the `:latest` tag on Docker Hub to mean latest release and introduce the `:nightly` tag for the per-master builds. This is in alignment with other Sentry projects. Should address getsentry/publish#666.

breaking: Rename latest tag to nightly

---

.github/workflows/lint.yml

Using `pull_request.head.ref` does not work if the PR is made from a fork as the local repo credentials don't work for pulling from remote repos (obviously :D). This PR fixes that.

ci(lint): Make lint job work for external contributors

---

src/utils/git.ts

This change will limit the generated changelog entries to the current working directory, supporting monorepos with multiple different Craft configurations in them. It should have no effect on existing multi-repo use cases.

feat(changelog): Limit changes to current project folder

---

src/targets/github.ts

Due to `ora` not being able to handle multiple spinners, there's a suspicion that it interrupts our main `Promise.all` handler in some way, or with the retry process. This makes some releases somehow stuck. Funny enough, in 99% of cases they work on the first try during retry.
Before swapping `ora` for something else, I believe it's way easier to verify that this is the culprit by simply removing it entirely and leaving just the text itself. In the CI, where we look at those logs, there are no spinners anyway, and everything is logged one by one.
I removed `Verifying asset` text, as it looks redundant to me, due to a very clear error message in case something goes wrong. With the happy path, it provides no value.
Also used `process.stderr.write` instead of `console.error` (which is an …

ref: Remove spinners from github target artifacts upload

---

src/targets/github.ts

GH Support suggested that our issues might be caused by too many requests in quick succession.
This change would verify this claim, but I'm still discussing this possibility with them.

ref: Upload GitHub artifacts in series

---

src/utils/githubApi.ts

This will allow us to see debug output of requests going out to GitHub.

ref: Allow for all logger levels in Octokit

---

src/targets/crates.ts

The crates target is not able to resume a workspace publish because already published crates cannot be republished. This means a partially successful publish cannot be retried.
To work around this, the `crates` target can skip publishing a crate if it already exists in this version. The downside of this is that we would silence errors when publishing the wrong version.
See https://github.com/getsentry/publish/issues/1070#issuecomment-1122077509

fix(crates): Resume workspace publish

---

src/commands/__tests__/prepare.test.ts
src/commands/prepare.ts

This PR also adds tests to the `checkVersionOrPart` function, this is largely for my own piece of mind that I haven't broken anything, let me know if these should be changed or removed (I acknowledge they aren't the most useful tests in the world).

Add additional context to error when version has a 'v' prefix

---

src/artifact_providers/__tests__/github.test.ts
src/artifact_providers/github.ts

This change will add a delay between retries to look for artifacts.
This should help to address the issues raised in https://github.om/getsentry/publish/issues/1209 which appears to be caused by a race condition between artifacts being uploaded and GitHub's API returning those artifacts.
NOTE: The additional tests ensure the logic for handing pagination and revision date work as expected.

Adding delay between retries for getting artifacts.

---

.github/workflows/build.yml
.github/workflows/release.yml

This should address the node and set-output / save state deprecation warnings.

Bump action versions

---

yarn.lock

idk why dependabot couldn't just do this

upgrade minimatch

---

Dockerfile

The [release 1.8.0](https://github.com/getsentry/symbol-collector/releases/tag/1.8.0) contains some fixes
Including to this issue that's still coming from `craft` runs: 
https://sentry.io/organizations/sentry/issues/3061145532/?project=5953213
Does CI smoke test the commands? I tested the Android and macOS builds of 1.8.0 but not on Linux.

Bump symbol collector

---

src/targets/nuget.ts

Adds `dotnet --version` and `dotnet nuget --version` info to the publish output, and (hopefully) works around the bug that is failing this workflow:
https://github.com/getsentry/publish/actions/runs/3716669257/jobs/6303253135#step:10:176

Emit dotnet and nuget version info

---

src/targets/sentryPypi.ts

I *think* this'll fix:
```
[debug] POST /repos/getsentry/pypi/git/trees - 422 in 208ms
Error:  base_tree is not a valid tree oid
at /usr/local/bin/craft:425:45299
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async y.doExecute (/usr/local/bin/craft:427:74896)
```

sentry-pypi: fix trailing whitespace in git output

---

src/targets/sentryPypi.ts

should fix:
```
[debug] POST /repos/getsentry/pypi/git/commits - 422 in 216ms
Error:  Parent SHA does not exist or is not a commit object
at /usr/local/bin/craft:425:45299
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async y.doExecute (/usr/local/bin/craft:427:74896)
```

sentry-pypi: get the commit id, not the tree

---

src/targets/cocoapods.ts

Publishing a podspec depending on another recently published podspec failed with `None of your spec
sources contain a spec satisfying the dependency`; see [CI](https://github.com/getsentry/publish/actions/runs/3759470548/jobs/6389071876). This is fixed now by using the --synchronous flag when publishing, recommended in https://github.com/CocoaPods/CocoaPods/issues/9497.

fix: Publishing podspec depending on other podspec

---

README.md
src/targets/upm.ts

`annotatedTag` option has been removed at some point, and might only cause confusion now.

cleanup(github): Remove mentions of unused annotatedTag

---

README.md
src/targets/github.ts

_(The background and motivation for this change is in #445, but I've decided not to implement that proposal fully right now, and instead make a smaller step first.)_
This PR introduces a `tagOnly` option for `github` target. If set to `true`, then we don't create a full GitHub release, and instead only create a tag in the remote repository. The default is `false`.

feat(github): Allow to push a tag without a release

---

Dockerfile
README.md
src/targets/hex.ts
src/targets/index.ts

feat: Add hex target for publishing elixir packages

---

src/targets/__tests__/maven.test.ts
src/targets/maven.ts

We had a few publish runs for the sentry android gradle plugin failed because maven central (hosting for java packages) is recently very slow https://status.maven.org/. This PR attempts to increase the deadline limit from 30 to 60 mins, which hopefully can help.

chore(maven): Increase nexus polling deadline to 60 mins

---

Dockerfile

Closes https://github.com/getsentry/craft/issues/452
Install Flutter in the docker image.
Removing Dart because Flutter ships Dart already and they should be compatible.

Make Flutter available in the docker image

---

Dockerfile

prevent these errors in github actions:
```console
[info] Publishing version: "3.27.1"
[debug] Working directory: /github/workspace/__repo__
Error:  fatal: detected dubious ownership in repository at '/github/workspace/__repo__'
To add an exception for this directory, call:
git config --global --add safe.directory /github/workspace/__repo__
To add an exception for this directory, call:
git config --global --add safe.directory /github/workspace/__repo__
```
this setting isn't great, as written -- but this restores the previous behaviour to unblock releases -- perhaps a better, more well scoped list can be determined instead in the future

ref: allow all mounted directories to be considered "safe"

---

src/targets/nuget.ts

Adds support for publishing [Nuget Symbol Package files](https://learn.microsoft.com/nuget/create-packages/symbol-packages-snupkg) (`.snupkg` extension).
We'll need this to publish the .NET SDK repo, now that we start using them with https://github.com/getsentry/sentry-dotnet/pull/2166.

Support nuget snupkg artifacts

---

src/targets/nuget.ts

In #458,  I added `.snupkg` files to the same list of artifacts as `.nupkg` files.  Unfortunately, this didn't work.  See https://github.com/getsentry/publish/issues/1857. The issue is that when publishing a `.snupkg`, nuget will 404 if the corresponding `.nupkg` has not yet been uploaded.
I though of just sorting the array, but that won't work because we use an array of promises when publishing, which won't guarantee that the first one is complete before the second one starts.
Switching to the original approach I started #458 with:  We'll just make sure the `.snupkg` artifact is downloaded (if there is one), so it will be in the same folder as the `.nupkg` file.  Then `dotnet nuget push` will automatically see them both when pushing the `.nupkg` and send the `.snupkg` only once the …

Push nuget nupkg and snupkg together

---

README.md
src/targets/__tests__/maven.test.ts
src/targets/maven.ts

This introduces some additions to be able to support a Kotlin Multiplatform publish. 
Additional artifacts include: `*.klib, *-all.jar, *-metadata.jar, *.module`.
Example artifacts of [Kermit](https://github.com/touchlab/Kermit):
- ios artifacts: https://repo1.maven.org/maven2/co/touchlab/kermit-sentry-iosarm64/1.2.0-M2/
- root artifacts: https://repo1.maven.org/maven2/co/touchlab/kermit-sentry/1.2.0-M2/
For context: for a KMP publish all platforms  need to be published and the root artifact contains metadata, see: https://github.com/getsentry/sentry-kotlin-multiplatform/pull/37#issuecomment-1219123937
The generated gpg command example:
root artifact:
```
"-Dfile=/var/folders/j2/r3dsjfkx4pj5n0v8jjlb6lv80000gn/T/craft-mSNdRu/sentry-kotlin-multiplatform-0.0.1/sentry-kotlin-multiplatform-0.0. …
```

feat: maven kotlin multiplatform support

---

.github/workflows/build.yml
Dockerfile
cloudbuild.yaml

needed this because `elixir` version on bullseye was too old.
ran the following inside container on both master and this branch
```bash
node --version
npm --version
dirmngr --version
ruby --version
gem --version
twine --version
java --version
mvn --version
iex --version
hex --version
dotnet --version
docker --version
cargo --version
gem info cocoapods
dart --version
flutter --version
```
```diff
➜  bump_craft_dockerfile diff -u old new
--- old	2023-07-12 17:06:57
+++ new	2023-07-12 17:18:55
@@ -1,24 +1,25 @@
-v14.21.3
-6.14.18
-dirmngr (GnuPG) 2.2.27
-Copyright (C) 2021 Free Software Foundation, Inc.
+v20.4.0
+9.7.2
+dirmngr (GnuPG) 2.2.40
+Copyright (C) 2022 g10 Code GmbH
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and …
```

feat(build): Bump Dockerfile base image to node:20-bookworm

---

.github/workflows/build.yml
Dockerfile
cloudbuild.yaml
src/targets/hex.ts

It seems publishing with 1.3.0 is broken - see https://getsentry.atlassian.net/browse/INC-456. 
Reverting all changes since 1.2.3 for now, so we can re-release this as 1.4.0 and then figure this out with more time.

Revert changes since 1.2.3

---

Dockerfile

this is needed by the sentry-pypi target
re-does #474 -- reverted in #475

ref: add python3-packaging explicitly

---

README.md
src/targets/brew.ts

This PR is a prerequisite for publishing sentry-wizard to brew (see https://github.com/getsentry/sentry-wizard/pull/406)
When artifact names contain versions (e.g. [sentry-wizard-v3.10.0.tgz](https://github.com/getsentry/sentry-wizard/releases/tag/v3.10.0)), it's not possible to access their checksums when publishing to brew, because mustache does not support nested variables. The template for brew formula would have to look something like this, but I couldn't find how to make it work for mustache:
```
sha256 "{{checksums.sentry-wizard-v{{version}}.tgz}}"
```
So this PR is simply replacing the version with `__VERSION__`, if it appears to be in the name of the artifact, when building the checksums dictionary.
Also updated readme to clarify the restrictions on the keys for checksums for the …

fix(brew): Replace version in artifact names with '__VERSION__' to access checksums from mustache

---

README.md
src/targets/__tests__/commitOnGitRepository.test.ts
src/targets/commitOnGitRepository.ts

- Limit valid repository URLs to only https. This is technically breaking but impact is marginal and it was likely never working in the first place.
- Allow for authentication when cloning and pushing via a GitHub PAT token via the `GITHUB_API_TOKEN` env variable.

feat(commit-on-git-repository): Allow for authentication in github

---

Gemfile
Gemfile.lock

We had to pin CocoaPods to v 1.13.0 and set activesupport to 7.0.8 because of a bug in activesupport. That bug is fixed with CocoaPods 1.14.2, so we can bump the version.
This is related to https://github.com/getsentry/craft/pull/496.

Bump CocoaPods from 1.13.0 to 1.14.2

---

Dockerfile

Updates to .NET 8 SDK which is currently on RC.2 (needed to release sentry-dotnet v4.0.0.alpha)

feat: use dotnet 8 SDK

---

src/targets/__tests__/github.test.ts
src/targets/github.ts

Automatically set `latest` for github releases only when the new version > the current latest version.
If we can't find a current latest, or something else goes wrong, we default to setting as latest.
Supersedes https://github.com/getsentry/craft/pull/502

feat(github): Only set `latest` when new version > old version

---

Dockerfile

Reverts getsentry/craft#501
.NET 8 has been released, dropping RC from Docker
Unblocks: https://github.com/getsentry/publish/actions/runs/6897440087/job/18765597452
cc @vaind

Use mainline .NET 8 SDK

---

README.md
src/targets/__tests__/npm.test.ts
src/targets/npm.ts

This updates the `npm` target with the following new behavior:
* If the new config for the npm target `checkPackageName` is defined, we check the current version of this package on npm
* If this version is newer than the to-be-published version, we tag it as "old" instead of "latest".
This supersedes https://github.com/getsentry/craft/pull/502.

feat(npm): Allow to configure `checkPackageName` for npm target

---

Dockerfile

> dotnet: Install the [7.0.100] .NET SDK or update [/github/workspace/__repo__/global.json] to match an installed SDK.
https://github.com/getsentry/publish/actions/runs/6962570877/job/18946542580
To release patches from the `main` branch we still need net7.
net8 is required for the feature branch/new major 4.0.0 that's going out with betas.
https://github.com/getsentry/publish/actions/runs/6962570877/job/18946542580

install net7 in addition to net8

---

src/utils/__tests__/version.test.ts
src/utils/version.ts

fixes the problem found here: https://github.com/getsentry/publish/issues/3360#issuecomment-1927658029

ref: handle comparison of two numeric pre releases

---

.github/workflows/build.yml
Dockerfile

Another attempt at https://github.com/getsentry/craft/pull/472, which was reverted in https://github.com/getsentry/craft/pull/475. This time the proximal reason is to get `twine` 4.0.
I'm assuming that
```
FROM node:14-buster-slim as builder
```
at the start of the Dockerfile can stay intact, is that correct?

build: Bump Dockerfile base image to node:20-bookworm

---

.github/workflows/build.yml
Dockerfile

This reverts commit 58ef1840bd4de556964c2549fa75e7fee271d8d5.
After updating, we saw publishing failures in `sentry-android-gradle-plugin` and `sentry-cli`. Logs attached for posterity.
[gradle-plugin-4.3.0.zip](https://github.com/getsentry/craft/files/14222150/gradle-plugin-4.3.0.zip)
[sentry-cli-2.28.1.zip](https://github.com/getsentry/craft/files/14222151/sentry-cli-2.28.1.zip)
[sentry-cli-2.28.2.zip](https://github.com/getsentry/craft/files/14222152/sentry-cli-2.28.2.zip)

build: Revert "build: Bump Dockerfile base image to node:20-bookworm (#511)"

---

Dockerfile

Instead of using the (outdated) debian package, install `twine` directly from pypi in a more recent version.

Install/update `twine` from pypi

---

src/targets/__tests__/pypi.test.ts
src/targets/pypi.ts

I suspect pypi can't handle parallel requests

ref: upload to twine synchronously in a single call

---

CHANGELOG.md
src/targets/__tests__/registry.test.ts
src/targets/registry.ts

We want to use the data from our release registry more, one info that is missing today is the timestamp of when something was released.
Yes, in theory, it exists in git, but just for convenience, we want to add a key `createdAt` into every JSON that the Registry target writes for easier access later.

feat: Add `createdAt` key to json in registry

---

src/targets/__tests__/maven.test.ts
src/targets/maven.ts

E.g. [sentry-native](https://github.com/getsentry/sentry-native/releases/tag/0.7.3) provides a `sentry-native.zip` file which is just a source bundle and not a maven artifact.

fix(maven): ignore artifacts which contain no POM/BOM

---

src/targets/__tests__/mavenDiskIo.test.ts
src/targets/maven.ts

Currently various SDKs (sentry-java, kotlin multiplatform) generate maven ready artifacts which contain a `module.json` file instead of a e.g. `sentry-java-1.0.0.module` file. 
This PR simply renames the file right before publishing to maven.

fix(maven): Rename module.json to dist.module

---

Dockerfile

Currently Flutter `3.10.0` is packaged with Dart `3.0.0`.
Now we require Dart `3.1.0` which is packaged starting with Flutter `3.13.0`
See: https://github.com/getsentry/publish/actions/runs/9548988953/job/26317502315#step:11:104

Upgrade Flutter from 3.10.0 to 3.13.0 in docker image

---

Dockerfile

This is required because we have an implicit dependency on a new core packate:web
```
Target of URI doesn't exist: 'package:web/web.dart'. Try creating the file referenced by the URI, or try using a URI for a file that does exist. - uri_does_not_exist
```

chore: update flutter to the latest version

---

README.md
src/targets/__tests__/pubDev.test.ts
src/targets/pubDev.ts

This will be necessary for a while because we keep the new dart core package `package:web` dependency implicit in order to keep the pacakge compatible with old Dart/Flutter SDK users. Some context in https://github.com/getsentry/sentry-dart/pull/2113

feat: add skipValidation to dart publishing

---

src/targets/__tests__/maven.test.ts
src/targets/maven.ts

We have recently set up a multiple maven target setup in one of our repos: https://github.com/getsentry/sentry-kotlin-multiplatform/blob/main/.craft.yml
and noticed an error during publish that indicates an error within the `importGPGKey` function: https://github.com/getsentry/publish/actions/runs/10250810494/job/28357374501#step:11:166
The `importGPGKey` function returns a promise but is not being awaited in the constructor (which is problematic when multiple targets are instantiated) and it cannot be awaited in a constructor so we move it to the publish call site

fix(maven): move `importGPGKey` function call from constructor to `publish`

---

.vscode/settings.json
README.md
src/utils/__tests__/changelog.test.ts
src/utils/changelog.ts

Right now this is manually done by the getsentry/sentry-python team. I thought it was a good opportunity improve automatic changelog generation. Thanks to @sentrivana for the idea.

feat: Add #body-in-changelog option to PR/commit bodies

---

README.md
src/targets/docker.ts

~~When available~~ Uses docker buildkit to copy images, this also handles multi arch images correctly. Docker publishes without buildkit installed will fail now.
Fixes: #541

ref(docker): Use docker buildx (BuildKit) to publish docker images

---

Dockerfile

https://github.com/getsentry/craft/pull/556 did not add buildx to the docker image - testing was done with a local install of craft using docker buildx on the host mac
failure surfaced here https://github.com/getsentry/publish/actions/runs/11374854272/job/31644383372
(the error says `docker: unknown flag: --tag` but it comes from `['buildx', 'imagetools', 'create', '--tag', targetImage, sourceImage],`)
previous success on sep 16 which was before that pr merged: https://github.com/getsentry/publish/actions/runs/10892013864/job/30224172979
this will probably fix but ci doesn't cover any of this

fix(docker): install buildx

---

src/utils/__tests__/changelog.test.ts
src/utils/changelog.ts

fix: Add optional to type chain

---

src/utils/__tests__/version.test.ts

This PR adds some tests for version helper functions used in multiple craft targets.
This came up after investigating https://github.com/getsentry/sentry-docs/issues/11716 where I found out that we have a specific list of pre-release suffix identifiers that we consider a pre-release, instead of considering every kind of `-x` suffix as a pre-release. 
Specifically, as mentioned in https://github.com/getsentry/craft/pull/561#discussion_r1836934373,  we don't consider the (shorthand) python post release pattern (TIL) a pre-release, although `parseVersion` actually puts it into the returned `.pre` property. 
Tests added:
- `parseVersion` parses Python post release values
- `isValidVersion` returns `true` for Python post releases
- `isPreviewVersion` returns `false` for Python post releases
- …

test(utils): Add additional tests for version helper functions

---

Dockerfile

.NET 9 was released 4 days ago: https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-9/overview
The `main` branch still relies on older .NET versions, so keeping the current ones, and installing .NET 9
Once we merge this into `main`, we can remove the older versions.
* https://github.com/getsentry/sentry-dotnet/pull/3591
Unblocks: https://github.com/getsentry/publish/issues/4608 (an alpha release from a branch that will merge onto itself)
FYI @jamescrosswell

Install .NET 9 SDK

---

Gemfile

Explain why we can't use cocoapods 1.16.2 and link a related GH issue.
Follow up on https://github.com/getsentry/craft/pull/569.

chore: Comment why we can't use cocoapods 1.16.2

---

Dockerfile

.NET 9 was added here: https://github.com/getsentry/craft/pull/564/
.NET 8 still needed to publish v4
.NET 7 can go away

remove dotnet 7

---

Dockerfile

The existing package paths for the compiled Erlang binaries
are no longer valid. This patch fixes them with the new ones
and fixes Docker image building.
Note that we are using the binaries compiled for Debian `bullseye`
instead of our `bookworm` version as they are not available yet.
One needs to check https://www.erlang-solutions.com/downloads/#

fix(docker): Use proper Erlang binaries for our builds

---

src/utils/awsLambdaLayerManager.ts

Since adding the `lambda:ListLayerVersions`, node layers have not been published correctly: https://github.com/getsentry/publish/actions/runs/12293170800/job/34305323121#step:11:1175
The python layers have not been released yet with version `2.3.0` of craft so are not affected.

fix(aws-lambda): Remove `lambda:ListLayerVersions` permission as it breaks publishing

---

src/targets/github.ts

Fixes https://github.com/getsentry/craft/pull/503#discussion_r1852239403
Note: We already have a test covering that `getLatestRelease()` accepts undefined.

fix(github): Guard against missing release

---

src/targets/github.ts

This PR updates the github release creation to ensure that the release is correctly marked as latest.
We used to set this for when we created the release draft, but according to https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release, this cannot actually be set on drafts. Instead, we need to set it when we publish the release.
There is also an option `legacy`, which, according to the docs, _seems_ like it may also work:
> `legacy` specifies that the latest release should be determined based on the release creation date and higher semantic version.
But since this option is a legacy option, _and_ since the behavior is a bit under-specced (e.g. if it determines based on creation date, it may be wrong, if it always uses semantic version, it may be correct), …

fix(github): Fix making github releases latest or not

---

src/targets/upm.ts

When I added the UPM target `preview releases` were not even a thing I considered. There's no reason to force this to `false`.

feat: Allow prereleases in UPM target

---

src/targets/upm.ts

Since `makeLatest` in `publishRelease` defaults to `true`, attempting to publish a pre-release results in 
```
Error:  Validation Failed: ***"resource":"Release","code":"custom","message":"Latest release cannot be draft or prerelease."***
```

fix: Allow UPM target to release pre-releases

---

src/targets/__tests__/maven.test.ts
src/targets/maven.ts

We have some repositories that do not use Gradle for publishing and therefore do not have the `.module` file, so we''re just checking for its presence before mentioning it to the `./mvnw gpg...` command

fix(maven): Do not try to publish `.module` file when does not exist

---

package.json
src/targets/awsLambdaLayer.ts
src/targets/ghPages.ts
src/targets/registry.ts
src/targets/upm.ts
src/utils/githubApi.ts

Currently we are using `https://username:token@github/owner/repo` to perform auth will talking to GitHub, it does not work well with GitHub Apps, hence deprecating it and bake the authentication token into authentication headers.

fix:(GitHub Auth): Deprecate getAuthUsername

---

src/targets/awsLambdaLayer.ts
src/targets/ghPages.ts
src/targets/registry.ts
src/targets/upm.ts
src/utils/githubApi.ts

This reverts commit d66030d6d7180ab33e878493c4be0e6c865bb8ab.
PR breaks the publishing to registry part, reverting to get people unblocked

Revert "fix:(GitHub Auth): Deprecate getAuthUsername (#585)"

---

src/targets/awsLambdaLayer.ts
src/targets/ghPages.ts
src/targets/registry.ts
src/targets/upm.ts
src/utils/githubApi.ts

Restore `getAuthUsername` and pass `placeholderusername` if not found
Locally tested it with Simple-git and a GitHub App token.  Confirmed Anthony's theory that the `username` field in `https://username:token@github.com/owner/repo.git` does not matter for both clone and push, so returning `placeholderusername` when no user is tied to a token, which usually is the case when it's a GitHub App token.

fix(): GitHub username not found when pushing to registry

---

Dockerfile

Our CI workflows for getsentry/streams and getsentry/arroyo most
recently started to write wheel metadata that is not compatible with
this version of twine.
We could pin wheel in arroyo and streams, but most likely other
workflows are also broken.

ref: Bump twine

---

Dockerfile

This should fix the Elixir release issues: https://github.com/getsentry/publish/actions/runs/13697376301/job/38302799587#step:12:94

feat: Install most recent Erlang from RabbitMQ packages

---

src/targets/nuget.ts

Resolves #598:
- https://github.com/getsentry/craft/issues/598
Pinning the version of of the .NET SDK used to build the sentry-dotnet repo prevents us from making relases, since that version of .NET is not installed on the machine that publishes NuGet packages.
We can run `dotnet push` using any version of .NET so this PR simply runs that command from outside the repository working directory.

fix: Avoid global.json when running `dotnet push`

---

src/targets/maven.ts

This is a [temporary measure](https://central.sonatype.org/publish/publish-portal-ossrh-staging-api) until we start supporting publishing to the central repo in #606.

chore(maven): Update base url to support publishing to central portal

---

.github/workflows/build.yml
.github/workflows/enforce-license-compliance.yml
.github/workflows/image.yml
.github/workflows/lint.yml
.github/workflows/release.yml

- Pin the GitHub Actions used to avoid dependency attacks.
- Set appropriate `permissions` scope for action steps.

gha: pin action versions to sha and set permissions

---

README.md
src/targets/__tests__/maven.test.ts
src/targets/maven.ts

For KMP we are going to publish new targets: `js`, `wasm-js`, `linux`, `mingw` and all the artifacts to publish are currently not compatible with the KMP implementation in craft -> they would be processed incorrectly with the current implementation
All these distributions have the same structure so we can add a new config that targets these. They all contain 5 files: 1 -source.jar, 1 -javadoc.jar, 1 .klib, 1 .module and 1 pom file.

feat(maven): add new config to process klib distributions differently from root and apple

---

src/targets/awsLambdaLayer.ts
src/utils/__tests__/awsLambdaLayerManager.test.ts
src/utils/awsLambdaLayerManager.ts

This allows users to easily identify which SDK version they use by looking at the description of the layer.
Also boosts confidence that you have input the correct ARN when adding the layer.

feat(aws-lambda): Add description including SDK version to layer metadata

---

src/commands/prepare.ts
src/utils/__tests__/git.test.ts
src/utils/git.ts

fix: Don't fail when there are no releases

---

README.md
src/targets/nuget.ts

See:
* https://github.com/getsentry/craft/pull/571#issuecomment-3358211891
#skip-changelog

chore(nuget): clarify publish behavior reentrant
