- package.json
- src/commands/publish.ts
- src/targets/brew.ts
- src/targets/github.ts
- src/utils/__tests__/github_api.test.ts
- src/utils/github_api.ts
- yarn.lock
TypeScript types are out of sync with the release ¯\\_(ツ)_/¯
> fix: Update deprecated octokit API calls

- CHANGELOG.md
- README.md
- src/targets/github.ts
Sorry for the reformat of readme and changelog, some autoformatter 🤷‍♂️ 
This change still needs to be tested in the wild, but it should create annotated tags from now on.
> feat: Add annoated tags by default

- src/targets/crates.ts
> fix(crates): Avoid a bug that causes empty crates

- package.json
- src/commands/prepare.ts
- src/commands/publish.ts
- src/stores/__tests__/zeus.test.ts
- src/stores/zeus.ts
- src/targets/base.ts
- src/targets/brew.ts
- src/targets/github.ts
- src/targets/registry.ts
- src/utils/__tests__/filters.test.ts
- yarn.lock
If `statusProvider` is github, we do not by default ask Zeus for artifacts.
Also for each target, if `includeNames` is not defined we skip artifacts check on Zeus as well.
> feat: Optional artifact check

- src/__tests__/config.test.ts
Tests for config, not config for tests.
> fix(docs): Clarify purpose of `config.test.ts`

- README.md
- src/config.ts
- src/targets/gcs.ts
No functionality change here - just fixing a few copy-pasta bits and clarifying a few docstrings and variable names. PR'ing this separately to make future PRs (where things _do_ change in a meaningful way) less noisy.
> ref(docs): Small language tweaks to existing GCS code

- src/commands/__tests__/prepare.test.ts
- src/utils/__tests__/gcsAPI.test.ts
- src/utils/__tests__/system.test.ts
Makes tests assume less about the platform :)
> test(windows): Fix tests on Windows

- .craft.yml
- CHANGELOG.md
- src/status_providers/base.ts
- src/status_providers/github.ts
Fixes #39 
+ minor refactoring and some docs.
> fix(github): Ignore pending response from legacy commit check API

- CHANGELOG.md
- src/artifact_providers/zeus.ts
- src/commands/artifacts_cmds/download.ts
- src/commands/artifacts_cmds/list.ts
- src/commands/publish.ts
- src/stores/__tests__/zeus.test.ts
- src/stores/zeus.ts
> fix(zeus): Don't force ZEUS_API_TOKEN when Zeus is not used

- CHANGELOG.md
- README.md
- src/targets/docker.ts
- src/targets/index.ts
This change adds a "docker" target which pulls an already built
source image tagged with the revision being released, tags it with
the new version, and pushes to a new target.
> feat(target): Add "docker" target

- CHANGELOG.md
- action.yml
- src/utils/__tests__/gcsAPI.test.ts
- src/utils/__tests__/noInput.test.ts
- src/utils/gcsApi.ts
- src/utils/noInput.ts
See https://github.com/getsentry/relay/runs/773764935?check_suite_focus=true for context.
> build(ci): Have better defaults for CI environments

- src/utils/__tests__/changes.test.ts
- src/utils/changes.ts
Fixes https://github.com/getsentry/craft/issues/138
> fix(changelog): Support subheadings

- CHANGELOG.md
- src/commands/publish.ts
Fixes #141, follow up to #137 where there was a forgotten negation causing this issue.
Tests will follow in a separate PR.
> fix(publish): Fix error when special target 'all' is used

- CHANGELOG.md
- Dockerfile
Unrelated to this change, apt installs are now indented for readability.
> feat(docker): Support cocoapods in the docker container

- Dockerfile
> feat: Upgrade gem to 3.1.5 to support GEM_HOST_API_KEY

- src/targets/registry.ts
Fixes a regression from #168.
cc @iker-barriocanal
> fix(remote): Clone with auth

- src/commands/publish.ts
The current wording led me to think that I'm missing something, but this is an optional script file, hence this would make more sense IMO.
> Fix: wording for optional post-release script file

- README.md
> docs: Document the `id` field in target config

- .craft.yml
Fixes https://github.com/getsentry/publish/runs/2421003416?check_suite_focus=true#step:9:319
> fix: Fix requireNames config for publish step

- src/targets/registry.ts
This PR salvages the non-controversial parts of #241:
- Better, more modular code organization
- Better/more typing
- Do a single clone/checkout for all registry
> ref(registry): Refactor RegistryTarget

- src/targets/github.ts
Fixes this embarrassment: https://github.com/getsentry/publish/runs/2686847139?check_suite_focus=true#step:8:49
(when the project explicitly sets `changelogPolicy: none`)
> fix(github-target): Don't die when changelog is N/A

- CHANGELOG.md
- src/targets/registry.ts
Follow up to #249.
Fixes https://github.com/getsentry/publish/actions/runs/925201945
> fix(registry): Fix onlyIfPresent config on batch

- Dockerfile
It was instrumented with Sentry's performance and Release Health features:
> use symbol collector 1.4.0

- .github/workflows/build.yml
- package.json
- tsconfig.build.json
> build: Drop Node 12 support, target Node 14

- src/targets/maven.ts
> fix: Correctly set auth header and content-type for Nexus requests

- src/targets/__tests__/maven.test.ts
- src/targets/maven.ts
> misc: Add explanatory code comments for Maven target

- src/targets/__tests__/pubDev.test.ts
- src/targets/pubDev.ts
> fix: Make sure dart credentials directory exists before writing

- .github/workflows/enforce-license-compliance.yml
> Use a custom action

- package.json
- yarn.lock
> upgrade(simple-git): Use latest version, 3.6.0

- README.md
- src/targets/github.ts
- src/utils/git.ts
https://github.blog/changelog/2022-04-25-git-io-deprecation/
> GitHub is sunsetting git.io

- Dockerfile
For context: https://github.com/getsentry/publish/actions/runs/3493924667/jobs/5849244708#step:10:768
> bump dotnet 7

- src/targets/__tests__/sentryPypi.test.ts
- src/targets/index.ts
- src/targets/sentryPypi.ts
I don't know if this works, going to leave it undocumented until I can actually ensure it works correctly (and I can hook up the auto-merge part in `getsentry/pypi`)
> add sentry-pypi target

- src/targets/cocoapods.ts
Add missing comma, see https://github.com/getsentry/craft/pull/442#discussion_r1062306451.
#skip-changelog
> ref: Add missing comma to Cocoapods

- Dockerfile
Fix https://github.com/getsentry/publish/issues/1828
> Error:  Error creating target instance for pub-dev!
> Error:  Executable "dart" not found. Is it installed?
> Fix extracting flutter file to tmp folder instead of current folder

- src/targets/maven.ts
Add missing await that breaks the release
> fix(maven): missing await for async kmp distribution func

- Dockerfile
Context https://github.com/getsentry/publish/actions/runs/4992675160/jobs/8940691809
Requires Dart 3 which is part of Flutter 3.10
> Upgrade Flutter to 3.10 in the docker image

- src/targets/hex.ts
see https://github.com/getsentry/publish/actions/runs/5521640240/jobs/10070045304#step:10:90
> fix(hex): Need local.hex --force for compiling deps

- Dockerfile
this regressed in #472 it seems
> ref: add python3-packaging explicitly

- Dockerfile
- src/targets/hex.ts
> Revert "feat(elixir): Use asdf to install erlang and elixir"

- Dockerfile
https://github.com/getsentry/symbol-collector/compare/1.8.0...1.12.0
> Bump symbol collector 1.12.0

- .github/workflows/build.yml
- .github/workflows/lint.yml
this thing is far too flaky -- and setup-node supports the volta key
> ref: remove volta from CI

- yarn.lock
this resolves a silly dependabot alert
> upgrade nock

- .github/workflows/build.yml
- Dockerfile
- package.json
this is a stepping stone to get to a more modern docker / node
> ref: upgrade to node 16

- Dockerfile
https://github.com/getsentry/symbol-collector/compare/1.12.0...1.17.0
> bump symbol collector 1.17.0

- src/targets/__tests__/maven.test.ts
- src/targets/maven.ts
Fixes https://github.com/getsentry/sentry-java/issues/2233
Depends on https://github.com/getsentry/sentry-java/pull/3422
> feat: Publish Gradle module metadata for Maven targets

- Dockerfile
> feat: Add rsync to Docker image

- src/targets/__tests__/upm.test.ts
Replacing the token with a test-token.
> chore: Updated `upm` test

- CONTRIBUTING.md
- README.md
> docs: Add contribution guidelines

- .github/workflows/image.yml
Fixing permissions here. This need packages `write` in order to push the container to GHCR.
> gha: image build needs package write
